/* ----- Third Party Imports ----- */
import { ClerkProvider } from "@clerk/nextjs";
import Link from "next/link";

/* ----- Project Imports ----- */
import Footer from "@/components/Footer";
import "./globals.css";

export const metadata = {
  title: "Wordly by the Lads",
  description: "Generated by Wordle Team Legends",
};

export default async function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
