/* ----- Third Party Imports ----- */
import {
  ClerkProvider,
  UserButton,
  auth,
  currentUser,
  clerkClient,
  getAuth,
} from "@clerk/nextjs";
import Link from "next/link";
import GameContextProvider from "@/context/game-context";

/* ----- Project Imports ----- */
import LoginManager from "@/components/LoginManager";
import "./globals.css";

export const metadata = {
  title: "Wordly by the Lads",
  description: "Generated by Wordle Team Legends",
};

export default async function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
